name: Build Tweak
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: theos/theos-action@v1
      - run: make package FINALPACKAGE=1
      - uses: actions/upload-artifact@v4
        with:
          name: BelieveFTMods-deb
          path: packages/*.deb
